# Generated by Django 3.2.10 on 2022-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookappModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=50)),
                ('Bid', models.IntegerField()),
                ('Author', models.CharField(max_length=50)),
                ('Read_by', models.CharField(max_length=50)),
            ],
        ),
    ]
